# Generated by Django 5.2.1 on 2025-05-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ventas', 'Ventas')], max_length=20),
        ),
    ]
